import React, { useEffect, useState, useMemo } from "react";
import { useNavigate } from "react-router-dom";
import { apiService } from "@/services/apiService";
import { useSystemSettings } from "@/contexts/SystemSettingsContext";
import AutoGenerateDialog from "./AutoGenerateDialog";
import {
  Calendar,
  Clock,
  Users,
  MapPin,
  BookOpen,
  Plus,
  Search,
  RefreshCw,
  Eye,
  Trash2,
  Grid3X3,
  List,
  X,
  Smartphone,
  Pencil,
  Wand2,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { toast } from "@/components/ui/use-toast";

type Origin = "auto" | "manual";

interface Schedule {
  schedule_id: string;
  school_year: string;
  semester: string;
  subj_code: string;
  subj_name: string;
  professor_name: string;
  section_name: string;
  schedule_type: string;
  start_time: string;
  end_time: string;
  days: string[];
  room_number: string | null;
  room_type: string | null;
  level: string;
  strand: string;
  origin: Origin;
}

interface Professor {
  id: string;
  name: string;
}

interface SimpleFilters {
  search: string;
  professor: string;
  level: string;
  strand: string;
}

type ViewMode = "cards" | "table";
type TabFilter = "all" | "auto" | "manual";

const deriveOrigin = (raw: any): Origin => {
  if (
    raw?.is_auto_generated === true ||
    raw?.auto_generated === true ||
    raw?.generated_by === "auto" ||
    raw?.created_by === "system" ||
    raw?.origin === "auto"
  ) {
    return "auto";
  }
  return "manual";
};

const ScheduleManagement: React.FC = () => {
  const { settings } = useSystemSettings();
  const navigate = useNavigate();

  const [schedules, setSchedules] = useState<Schedule[]>([]);
  const [professors, setProfessors] = useState<Professor[]>([]);
  const [loading, setLoading] = useState(true);
  const [viewMode, setViewMode] = useState<ViewMode>("cards");

  const [selectedSchedule, setSelectedSchedule] = useState<Schedule | null>(null);
  const [isDetailsOpen, setIsDetailsOpen] = useState(false);
  const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const [scheduleToDelete, setScheduleToDelete] = useState<string | null>(null);
  const [isSyncing, setIsSyncing] = useState(false);

  const [isAutoDialogOpen, setIsAutoDialogOpen] = useState(false);
  const [isChecking, setIsChecking] = useState(false);

  const [filters, setFilters] = useState<SimpleFilters>({
    search: "",
    professor: "all",
    level: "all",
    strand: "all",
  });

  const [tab, setTab] = useState<TabFilter>("all");

  const [isEditProfOpen, setIsEditProfOpen] = useState(false);
  const [scheduleToEdit, setScheduleToEdit] = useState<Schedule | null>(null);
  const [selectedProfessorId, setSelectedProfessorId] = useState<string>("");

  const stats = useMemo(() => {
    const total = schedules.length;
    const dayNames = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"];
    const todayName = dayNames[new Date().getDay()];
    const todaySchedules = schedules.filter((s) => s.days.some((d) => d.toLowerCase() === todayName)).length;
    const autoCount = schedules.filter((s) => s.origin === "auto").length;
    const manualCount = schedules.filter((s) => s.origin === "manual").length;
    return { total, today: todaySchedules, auto: autoCount, manual: manualCount };
  }, [schedules]);

  const syncToMobile = async () => {
    setIsSyncing(true);
    try {
      const response = await apiService.syncToFirebase();
      if (response.success) {
        toast({ title: "Sync Successful", description: "Schedules have been synced to mobile app" });
      } else {
        toast({
          title: "Sync Failed",
          description: response.message || "Failed to sync to mobile app",
          variant: "destructive",
        });
      }
    } catch {
      toast({
        title: "Sync Error",
        description: "An error occurred while syncing to mobile app",
        variant: "destructive",
      });
    } finally {
      setIsSyncing(false);
    }
  };

  const filteredSchedules = useMemo(() => {
    return schedules.filter((schedule) => {
      if (tab !== "all" && schedule.origin !== tab) return false;
      if (filters.search) {
        const s = filters.search.toLowerCase();
        const ok =
          schedule.section_name.toLowerCase().includes(s) ||
          schedule.subj_code.toLowerCase().includes(s) ||
          schedule.subj_name.toLowerCase().includes(s) ||
          schedule.professor_name.toLowerCase().includes(s);
        if (!ok) return false;
      }
      if (filters.professor !== "all") {
        if (!schedule.professor_name.toLowerCase().includes(filters.professor.toLowerCase())) return false;
      }
      if (filters.level !== "all" && schedule.level !== filters.level) return false;
      if (filters.strand !== "all" && schedule.strand !== filters.strand) return false;
      return true;
    });
  }, [schedules, filters, tab]);

  const formatTime = (time: string) => {
    if (!time) return "";
    const [hours, minutes] = time.split(":");
    const hour = parseInt(hours, 10);
    return `${hour % 12 || 12}:${minutes} ${hour >= 12 ? "PM" : "AM"}`;
  };

  const getOriginBadge = (origin: Origin) => {
    return origin === "auto" ? (
      <Badge className="bg-indigo-100 text-indigo-800 border-indigo-200">Auto</Badge>
    ) : (
      <Badge className="bg-amber-100 text-amber-800 border-amber-200">Manual</Badge>
    );
  };

  const fetchSchedules = async () => {
    setLoading(true);
    try {
      const response = await apiService.getSchedules({
        school_year: settings.schoolYear,
        semester: settings.semester,
      });
      if (response.success && Array.isArray(response.data)) {
        const mapped = response.data.map((schedule: any) => ({
          schedule_id: schedule.schedule_id?.toString?.() ?? String(schedule.schedule_id),
          school_year: schedule.school_year,
          semester: schedule.semester,
          subj_code: schedule.subj_code,
          subj_name: schedule.subj_name,
          professor_name: schedule.professor_name,
          section_name: schedule.section_name,
          schedule_type: schedule.schedule_type,
          start_time: schedule.start_time,
          end_time: schedule.end_time,
          days: Array.isArray(schedule.days)
            ? schedule.days
            : typeof schedule.days === "string"
            ? (() => {
                try {
                  return JSON.parse(schedule.days);
                } catch {
                  return [];
                }
              })()
            : [],
          room_number: schedule.room_number,
          room_type: schedule.room_type,
          level: schedule.level || "",
          strand: schedule.strand || "",
          origin: deriveOrigin(schedule),
        }));
        setSchedules(mapped);
      }
    } catch {
      toast({ title: "Error", description: "Failed to load schedules", variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  const fetchProfessors = async () => {
    try {
      const response = await apiService.getProfessors();
      if (response.success && Array.isArray(response.data)) {
        const mapped = response.data
          .filter((p: any) => p && (p.prof_id || p.id))
          .map((p: any) => ({
            id: (p.prof_id || p.id).toString(),
            name: p.prof_name || p.name || "Unknown Professor",
          }));
        setProfessors(mapped);
      }
    } catch {}
  };

  const runAutomation = async (payload: any) => {
    setIsChecking(true);
    try {
      const res = await apiService.autoGenerate({
        ...payload,
        school_year: settings.schoolYear,
        semester: settings.semester,
      });
      if (res.success) {
        await fetchSchedules();
        toast({
          title: "Automation complete",
          description: res.message || "Generated schedules successfully.",
        });
        setIsAutoDialogOpen(false);
        setTab("auto");
      } else {
        toast({
          title: "Automation failed",
          description: res.message || "See server logs.",
          variant: "destructive",
        });
      }
    } catch (e: any) {
      toast({
        title: "Error",
        description: e?.message || "Automation error.",
        variant: "destructive",
      });
    } finally {
      setIsChecking(false);
    }
  };

  const deleteSchedule = async () => {
    if (!scheduleToDelete) return;
    try {
      const response = await apiService.deleteSchedule(parseInt(scheduleToDelete));
      if (response.success) {
        setSchedules((prev) => prev.filter((s) => s.schedule_id !== scheduleToDelete));
        toast({ title: "Success", description: "Schedule deleted successfully" });
      } else {
        toast({ title: "Error", description: "Failed to delete schedule", variant: "destructive" });
      }
    } catch {
      toast({ title: "Error", description: "Failed to delete schedule", variant: "destructive" });
    } finally {
      setIsDeleteOpen(false);
      setScheduleToDelete(null);
    }
  };

  const clearFilters = () => {
    setFilters({ search: "", professor: "all", level: "all", strand: "all" });
  };

  useEffect(() => {
    fetchSchedules();
    fetchProfessors();
  }, [settings.schoolYear, settings.semester]);

  const openEditProfessor = (schedule: Schedule) => {
    setScheduleToEdit(schedule);
    const currentProf = professors.find((p) => p.name === schedule.professor_name);
    setSelectedProfessorId(currentProf ? currentProf.id : "");
    setIsEditProfOpen(true);
  };

  const applyProfessorChange = async () => {
    if (!scheduleToEdit || !selectedProfessorId) {
      toast({
        title: "Missing selection",
        description: "Please choose a professor.",
        variant: "destructive",
      });
      return;
    }
    const newProf = professors.find((p) => p.id === selectedProfessorId);
    if (!newProf) {
      toast({
        title: "Invalid professor",
        description: "Please choose a valid professor.",
        variant: "destructive",
      });
      return;
    }

    try {
      const sid = parseInt(scheduleToEdit.schedule_id);
      const pid = parseInt(selectedProfessorId);
      const res = await apiService.updateScheduleProfessor(sid, pid);

      if (res?.success) {
        setSchedules((prev) =>
          prev.map((s) =>
            s.schedule_id === scheduleToEdit.schedule_id ? { ...s, professor_name: newProf.name } : s
          )
        );
        if (selectedSchedule && selectedSchedule.schedule_id === scheduleToEdit.schedule_id) {
          setSelectedSchedule({ ...selectedSchedule, professor_name: newProf.name });
        }
        toast({ title: "Updated", description: "Professor updated for this schedule." });
        setIsEditProfOpen(false);
      } else {
        toast({
          title: "Update failed",
          description: res?.message || "Server did not accept the change.",
          variant: "destructive",
        });
      }
    } catch (e: any) {
      toast({ title: "Error", description: e?.message || "Could not update professor.", variant: "destructive" });
    }
  };

  const renderScheduleCard = (schedule: Schedule) => (
    <Card key={schedule.schedule_id} className="hover:shadow-md transition-shadow">
      <CardHeader className="pb-3">
        <div className="flex items-start justify-between">
          <div>
            <CardTitle className="text-lg">{schedule.section_name}</CardTitle>
            <p className="text-sm text-muted-foreground">
              {schedule.level} - {schedule.strand}
            </p>
          </div>
          <div className="flex items-center gap-2">
            {getOriginBadge(schedule.origin)}
          </div>
        </div>
      </CardHeader>

      <CardContent className="space-y-3">
        <div className="flex items-center gap-2">
          <BookOpen className="h-4 w-4 text-muted-foreground" />
          <div>
            <p className="font-medium text-sm">{schedule.subj_code}</p>
            <p className="text-xs text-muted-foreground">{schedule.subj_name}</p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Users className="h-4 w-4 text-muted-foreground" />
          <p className="text-sm">{schedule.professor_name}</p>
        </div>

        <div className="flex items-center gap-2">
          <Clock className="h-4 w-4 text-muted-foreground" />
          <p className="text-sm">
            {formatTime(schedule.start_time)} - {formatTime(schedule.end_time)}
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Calendar className="h-4 w-4 text-muted-foreground" />
          <div className="flex flex-wrap gap-1">
            {schedule.days.map((day) => (
              <Badge key={day} variant="outline" className="text-xs">
                {day.slice(0, 3)}
              </Badge>
            ))}
          </div>
        </div>

        {schedule.room_number && (
          <div className="flex items-center gap-2">
            <MapPin className="h-4 w-4 text-muted-foreground" />
            <p className="text-sm">{schedule.room_number}</p>
          </div>
        )}

        <div className="flex gap-2 pt-2">
          <Button
            size="sm"
            variant="outline"
            onClick={() => {
              setSelectedSchedule(schedule);
              setIsDetailsOpen(true);
            }}
          >
            <Eye className="h-3 w-3 mr-1" />
            View
          </Button>
          <Button size="sm" variant="outline" onClick={() => openEditProfessor(schedule)}>
            <Pencil className="h-3 w-3 mr-1" />
            Change Professor
          </Button>
          <Button
            size="sm"
            variant="destructive"
            onClick={() => {
              setScheduleToDelete(schedule.schedule_id);
              setIsDeleteOpen(true);
            }}
          >
            <Trash2 className="h-3 w-3 mr-1" />
            Delete
          </Button>
        </div>
      </CardContent>
    </Card>
  );

  const renderScheduleTable = () => (
    <div className="rounded-lg border bg-white">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Section</TableHead>
            <TableHead>Subject</TableHead>
            <TableHead>Professor</TableHead>
            <TableHead>Time</TableHead>
            <TableHead>Days</TableHead>
            <TableHead>Room</TableHead>
            <TableHead>Origin</TableHead>
            <TableHead>Actions</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {filteredSchedules.map((schedule) => (
            <TableRow key={schedule.schedule_id}>
              <TableCell>
                <div>
                  <p className="font-medium">{schedule.section_name}</p>
                  <p className="text-xs text-muted-foreground">
                    {schedule.level} - {schedule.strand}
                  </p>
                </div>
              </TableCell>
              <TableCell>
                <div>
                  <p className="font-medium">{schedule.subj_code}</p>
                  <p className="text-xs text-muted-foreground">{schedule.subj_name}</p>
                </div>
              </TableCell>
              <TableCell>{schedule.professor_name}</TableCell>
              <TableCell>
                {formatTime(schedule.start_time)} - {formatTime(schedule.end_time)}
              </TableCell>
              <TableCell>
                <div className="flex gap-1">
                  {schedule.days.slice(0, 3).map((day) => (
                    <Badge key={day} variant="outline" className="text-xs">
                      {day.slice(0, 3)}
                    </Badge>
                  ))}
                  {schedule.days.length > 3 && (
                    <Badge variant="outline" className="text-xs">
                      +{schedule.days.length - 3}
                    </Badge>
                  )}
                </div>
              </TableCell>
              <TableCell>{schedule.room_number || "No Room"}</TableCell>
              <TableCell>{getOriginBadge(schedule.origin)}</TableCell>
              <TableCell>
                <div className="flex gap-1">
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => {
                      setSelectedSchedule(schedule);
                      setIsDetailsOpen(true);
                    }}
                  >
                    <Eye className="h-3 w-3" />
                  </Button>
                  <Button size="sm" variant="outline" onClick={() => openEditProfessor(schedule)}>
                    <Pencil className="h-3 w-3" />
                  </Button>
                  <Button
                    size="sm"
                    variant="destructive"
                    onClick={() => {
                      setScheduleToDelete(schedule.schedule_id);
                      setIsDeleteOpen(true);
                    }}
                  >
                    <Trash2 className="h-3 w-3" />
                  </Button>
                </div>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="container mx-auto py-6 px-4 space-y-6">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
          <div>
            <h1 className="text-2xl font-bold">Class Schedules</h1>
            <p className="text-muted-foreground">
              {settings.schoolYear} - {settings.semester}
            </p>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" onClick={fetchSchedules} disabled={loading}>
              <RefreshCw className={`mr-2 h-4 w-4 ${loading ? "animate-spin" : ""}`} />
              Refresh
            </Button>
            <Button
              variant="outline"
              onClick={syncToMobile}
              disabled={isSyncing}
              className="bg-blue-50 border-blue-200 text-blue-700 hover:bg-blue-100"
            >
              <Smartphone className={`mr-2 h-4 w-4 ${isSyncing ? "animate-pulse" : ""}`} />
              {isSyncing ? "Syncing..." : "Sync to Mobile"}
            </Button>
            <Button onClick={() => navigate("/scheduling/new")}>
              <Plus className="mr-2 h-4 w-4" />
              Add Schedule
            </Button>
            <Button variant="outline" onClick={() => setIsAutoDialogOpen(true)}>
              <Wand2 className="mr-2 h-4 w-4" />
              Auto-Generate
            </Button>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">Total Schedules</p>
                  <p className="text-2xl font-bold">{stats.total}</p>
                </div>
                <Calendar className="h-8 w-8 text-blue-500" />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">Today's Classes</p>
                  <p className="text-2xl font-bold">{stats.today}</p>
                </div>
                <Clock className="h-8 w-8 text-green-500" />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">Auto / Manual</p>
                  <p className="text-2xl font-bold">
                    {stats.auto} / {stats.manual}
                  </p>
                </div>
                <Wand2 className="h-8 w-8 text-indigo-500" />
              </div>
            </CardContent>
          </Card>
        </div>

        <Card>
          <CardContent className="p-4">
            <div className="flex flex-col md:flex-row gap-4">
              <div className="flex-1">
                <div className="relative">
                  <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                  <Input
                    placeholder="Search schedules..."
                    value={filters.search}
                    onChange={(e) => setFilters((prev) => ({ ...prev, search: e.target.value }))}
                    className="pl-10"
                  />
                </div>
              </div>

              <div className="flex gap-2">
                <Select
                  value={filters.professor}
                  onValueChange={(value) => setFilters((prev) => ({ ...prev, professor: value }))}
                >
                  <SelectTrigger className="w-[140px]">
                    <SelectValue placeholder="Professors" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All Professors</SelectItem>
                    {professors.map((prof) => (
                      <SelectItem key={prof.id} value={prof.name}>
                        {prof.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>

                <Select
                  value={filters.level}
                  onValueChange={(value) => setFilters((prev) => ({ ...prev, level: value }))}
                >
                  <SelectTrigger className="w-[100px]">
                    <SelectValue placeholder="Level" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All Levels</SelectItem>
                    <SelectItem value="11">Grade 11</SelectItem>
                    <SelectItem value="12">Grade 12</SelectItem>
                  </SelectContent>
                </Select>

                <Select
                  value={filters.strand}
                  onValueChange={(value) => setFilters((prev) => ({ ...prev, strand: value }))}
                >
                  <SelectTrigger className="w-[100px]">
                    <SelectValue placeholder="Strand" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All Strands</SelectItem>
                    <SelectItem value="STEM">STEM</SelectItem>
                    <SelectItem value="HUMSS">HUMSS</SelectItem>
                    <SelectItem value="GAS">GAS</SelectItem>
                    <SelectItem value="ABM">ABM</SelectItem>
                  </SelectContent>
                </Select>

                {(filters.search ||
                  filters.professor !== "all" ||
                  filters.level !== "all" ||
                  filters.strand !== "all") && (
                  <Button variant="outline" onClick={clearFilters}>
                    <X className="h-4 w-4" />
                  </Button>
                )}
              </div>
            </div>

            <div className="mt-4">
              <Tabs value={tab} onValueChange={(v) => setTab(v as TabFilter)}>
                <TabsList>
                  <TabsTrigger value="all">All</TabsTrigger>
                  <TabsTrigger value="auto">Auto-generated</TabsTrigger>
                  <TabsTrigger value="manual">Manual</TabsTrigger>
                </TabsList>
              </Tabs>
            </div>

            <div className="flex items-center justify-between mt-4">
              <p className="text-sm text-muted-foreground">
                Showing {filteredSchedules.length} of {schedules.length} schedules
              </p>
              <div className="flex gap-2">
                <Button
                  size="sm"
                  variant={viewMode === "cards" ? "default" : "outline"}
                  onClick={() => setViewMode("cards")}
                >
                  <Grid3X3 className="h-4 w-4" />
                </Button>
                <Button
                  size="sm"
                  variant={viewMode === "table" ? "default" : "outline"}
                  onClick={() => setViewMode("table")}
                >
                  <List className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>

        {loading ? (
          <div className="flex items-center justify-center h-64">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
          </div>
        ) : filteredSchedules.length === 0 ? (
          <Card>
            <CardContent className="p-12 text-center">
              <Calendar className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
              <h3 className="text-lg font-semibold mb-2">No schedules found</h3>
              <p className="text-muted-foreground mb-4">
                {schedules.length === 0
                  ? "Create your first schedule to get started."
                  : "Try adjusting your filters or switch tabs."}
              </p>
              <div className="flex justify-center gap-2">
                <Button onClick={() => navigate("/scheduling/new")}>
                  <Plus className="mr-2 h-4 w-4" />
                  Add Schedule
                </Button>
                <Button variant="outline" onClick={() => setIsAutoDialogOpen(true)}>
                  <Wand2 className="mr-2 h-4 w-4" />
                  Auto-Generate
                </Button>
              </div>
            </CardContent>
          </Card>
        ) : viewMode === "cards" ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {filteredSchedules.map(renderScheduleCard)}
          </div>
        ) : (
          renderScheduleTable()
        )}

        <Dialog open={isDetailsOpen} onOpenChange={setIsDetailsOpen}>
          <DialogContent className="max-w-md">
            <DialogHeader>
              <DialogTitle>Schedule Details</DialogTitle>
            </DialogHeader>

            {selectedSchedule && (
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="font-semibold text-lg">{selectedSchedule.section_name}</h3>
                    <p className="text-muted-foreground">
                      {selectedSchedule.level} - {selectedSchedule.strand}
                    </p>
                  </div>
                  {getOriginBadge(selectedSchedule.origin)}
                </div>

                <div className="space-y-3">
                  <div className="flex items-center gap-2">
                    <BookOpen className="h-4 w-4 text-muted-foreground" />
                    <div>
                      <p className="font-medium">{selectedSchedule.subj_code}</p>
                      <p className="text-sm text-muted-foreground">{selectedSchedule.subj_name}</p>
                    </div>
                  </div>

                  <div className="flex items-center gap-2">
                    <Users className="h-4 w-4 text-muted-foreground" />
                    <p>{selectedSchedule.professor_name}</p>
                  </div>

                  <div className="flex items-center gap-2">
                    <Clock className="h-4 w-4 text-muted-foreground" />
                    <p>
                      {formatTime(selectedSchedule.start_time)} - {formatTime(selectedSchedule.end_time)}
                    </p>
                  </div>

                  <div className="flex items-center gap-2">
                    <Calendar className="h-4 w-4 text-muted-foreground" />
                    <div className="flex gap-1">
                      {selectedSchedule.days.map((day) => (
                        <Badge key={day} variant="outline">
                          {day}
                        </Badge>
                      ))}
                    </div>
                  </div>

                  {selectedSchedule.room_number && (
                    <div className="flex items-center gap-2">
                      <MapPin className="h-4 w-4 text-muted-foreground" />
                      <p>{selectedSchedule.room_number}</p>
                    </div>
                  )}
                </div>
              </div>
            )}

            <DialogFooter className="gap-2">
              {selectedSchedule && (
                <Button variant="outline" onClick={() => openEditProfessor(selectedSchedule)}>
                  <Pencil className="h-4 w-4 mr-2" />
                  Change Professor
                </Button>
              )}
              <Button variant="outline" onClick={() => setIsDetailsOpen(false)}>
                Close
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        <AlertDialog open={isDeleteOpen} onOpenChange={setIsDeleteOpen}>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Delete Schedule</AlertDialogTitle>
              <AlertDialogDescription>
                Are you sure you want to delete this schedule? This action cannot be undone.
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Cancel</AlertDialogCancel>
              <AlertDialogAction onClick={deleteSchedule} className="bg-red-600 hover:bg-red-700">
                Delete
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>

        <AutoGenerateDialog
          open={isAutoDialogOpen}
          onOpenChange={setIsAutoDialogOpen}
          onRun={runAutomation}
          defaults={{ school_year: settings.schoolYear, semester: settings.semester }}
          loading={isChecking}
        />

        <Dialog open={isEditProfOpen} onOpenChange={setIsEditProfOpen}>
          <DialogContent className="max-w-sm">
            <DialogHeader>
              <DialogTitle>Change Professor</DialogTitle>
            </DialogHeader>
            <div className="space-y-3">
              <div className="text-sm">
                {scheduleToEdit ? (
                  <>
                    <div className="mb-1 font-medium">{scheduleToEdit.section_name}</div>
                    <div className="text-muted-foreground">
                      {scheduleToEdit.subj_code} — {scheduleToEdit.subj_name}
                    </div>
                  </>
                ) : null}
              </div>

              <Select value={selectedProfessorId} onValueChange={(v) => setSelectedProfessorId(v)}>
                <SelectTrigger>
                  <SelectValue placeholder="Select professor" />
                </SelectTrigger>
                <SelectContent>
                  {professors.map((p) => (
                    <SelectItem key={p.id} value={p.id}>
                      {p.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setIsEditProfOpen(false)}>
                Cancel
              </Button>
              <Button onClick={applyProfessorChange}>Save</Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    </div>
  );
};

export default ScheduleManagement;
