import React, { useEffect, useState, useMemo } from "react";
import { useNavigate } from "react-router-dom";
import { apiService } from "@/services/apiService";
import { useSystemSettings } from "@/contexts/SystemSettingsContext";
import AutoGenerateDialog from "./AutoGenerateDialog";
import {
  Calendar,
  Clock,
  Users,
  MapPin,
  BookOpen,
  Plus,
  Search,
  RefreshCw,
  Eye,
  Trash2,
  AlertTriangle,
  CheckCircle,
  Grid3X3,
  List,
  X,
  Smartphone,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { toast } from "@/components/ui/use-toast";

// Types
interface Schedule {
  schedule_id: string;
  school_year: string;
  semester: string;
  subj_code: string;
  subj_name: string;
  professor_name: string;
  section_name: string;
  schedule_type: string;
  start_time: string;
  end_time: string;
  days: string[];
  room_number: string | null;
  room_type: string | null;
  level: string;
  strand: string;
  conflicts?: ConflictInfo[];
}

interface ConflictInfo {
  type: "professor" | "room" | "section";
  message: string;
}

interface Professor {
  id: string;
  name: string;
}

interface SimpleFilters {
  search: string;
  professor: string;
  level: string;
  strand: string;
  status: string;
}

type ViewMode = "cards" | "table";

const ScheduleManagement: React.FC = () => {
  const { settings } = useSystemSettings();
  const navigate = useNavigate();

  // State
  const [schedules, setSchedules] = useState<Schedule[]>([]);
  const [professors, setProfessors] = useState<Professor[]>([]);
  const [loading, setLoading] = useState(true);
  const [viewMode, setViewMode] = useState<ViewMode>("cards");

  // Dialog states (form state removed)
  const [selectedSchedule, setSelectedSchedule] = useState<Schedule | null>(null);
  const [isDetailsOpen, setIsDetailsOpen] = useState(false);
  const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const [scheduleToDelete, setScheduleToDelete] = useState<string | null>(null);
  const [isSyncing, setIsSyncing] = useState(false);

  const [isAutoDialogOpen, setIsAutoDialogOpen] = useState(false);
  const [isChecking, setIsChecking] = useState(false); // realtime/batch check indicator

  // Simple filters
  const [filters, setFilters] = useState<SimpleFilters>({
    search: "",
    professor: "all",
    level: "all",
    strand: "all",
    status: "all",
  });

  // Stats
  const stats = useMemo(() => {
    const total = schedules.length;
    const conflicts = schedules.filter(
      (s) => s.conflicts && s.conflicts.length > 0
    ).length;
    const todaySchedules = schedules.filter((s) => {
      const dayNames = [
        "sunday",
        "monday",
        "tuesday",
        "wednesday",
        "thursday",
        "friday",
        "saturday",
      ];
      const todayName = dayNames[new Date().getDay()];
      return s.days.some((day) => day.toLowerCase() === todayName);
    }).length;

    return { total, conflicts, today: todaySchedules };
  }, [schedules]);

  // Sync to Firebase for mobile app
  const syncToMobile = async () => {
    setIsSyncing(true);
    try {
      const response = await apiService.syncToFirebase();

      if (response.success) {
        toast({
          title: "Sync Successful",
          description: "Schedules have been synced to mobile app",
          variant: "default",
        });
      } else {
        toast({
          title: "Sync Failed",
          description: response.message || "Failed to sync to mobile app",
          variant: "destructive",
        });
      }
    } catch (error) {
      console.error("Sync error:", error);
      toast({
        title: "Sync Error",
        description: "An error occurred while syncing to mobile app",
        variant: "destructive",
      });
    } finally {
      setIsSyncing(false);
    }
  };

  // Filtered schedules
  const filteredSchedules = useMemo(() => {
    return schedules.filter((schedule) => {
      // Search filter
      if (filters.search) {
        const searchTerm = filters.search.toLowerCase();
        const matchesSearch =
          schedule.section_name.toLowerCase().includes(searchTerm) ||
          schedule.subj_code.toLowerCase().includes(searchTerm) ||
          schedule.subj_name.toLowerCase().includes(searchTerm) ||
          schedule.professor_name.toLowerCase().includes(searchTerm);
        if (!matchesSearch) return false;
      }

      // Professor filter
      if (filters.professor !== "all") {
        if (
          !schedule.professor_name
            .toLowerCase()
            .includes(filters.professor.toLowerCase())
        ) {
          return false;
        }
      }

      // Level filter
      if (filters.level !== "all" && schedule.level !== filters.level) {
        return false;
      }

      // Strand filter
      if (filters.strand !== "all" && schedule.strand !== filters.strand) {
        return false;
      }

      // Status filter
      if (filters.status !== "all") {
        const hasConflicts =
          schedule.conflicts && schedule.conflicts.length > 0;
        if (filters.status === "conflict" && !hasConflicts) return false;
        if (filters.status === "good" && hasConflicts) return false;
      }

      return true;
    });
  }, [schedules, filters]);

  // Utility functions
  const formatTime = (time: string) => {
    if (!time) return "";
    const [hours, minutes] = time.split(":");
    const hour = parseInt(hours, 10);
    return `${hour % 12 || 12}:${minutes} ${hour >= 12 ? "PM" : "AM"}`;
  };

  const getStatusBadge = (schedule: Schedule) => {
    if (!schedule.conflicts || schedule.conflicts.length === 0) {
      return (
        <Badge className="bg-green-100 text-green-800 border-green-200">
          <CheckCircle className="w-3 h-3 mr-1" />
          Good
        </Badge>
      );
    }

    return (
      <Badge className="bg-red-100 text-red-800 border-red-200">
        <AlertTriangle className="w-3 h-3 mr-1" />
        Conflict
      </Badge>
    );
  };

  // API functions
  const fetchSchedules = async () => {
    setLoading(true);
    try {
      const response = await apiService.getSchedules({
        school_year: settings.schoolYear,
        semester: settings.semester,
      });

      if (response.success && Array.isArray(response.data)) {
        const mappedSchedules = response.data.map((schedule: any) => ({
          schedule_id: schedule.schedule_id.toString(),
          school_year: schedule.school_year,
          semester: schedule.semester,
          subj_code: schedule.subj_code,
          subj_name: schedule.subj_name,
          professor_name: schedule.professor_name,
          section_name: schedule.section_name,
          schedule_type: schedule.schedule_type,
          start_time: schedule.start_time,
          end_time: schedule.end_time,
          days: Array.isArray(schedule.days)
            ? schedule.days
            : typeof schedule.days === "string"
            ? JSON.parse(schedule.days)
            : [],
          room_number: schedule.room_number,
          room_type: schedule.room_type,
          level: schedule.level || "",
          strand: schedule.strand || "",
          conflicts: [], // We'll check conflicts separately for performance
        }));

        setSchedules(mappedSchedules);
      }
    } catch (error) {
      console.error("Error fetching schedules:", error);
      toast({
        title: "Error",
        description: "Failed to load schedules",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const fetchProfessors = async () => {
    try {
      const response = await apiService.getProfessors();
      if (response.success && Array.isArray(response.data)) {
        const mappedProfessors = response.data
          .filter((prof: any) => prof && (prof.prof_id || prof.id))
          .map((prof: any) => ({
            id: (prof.prof_id || prof.id).toString(),
            name: prof.prof_name || prof.name || "Unknown Professor",
          }));
        setProfessors(mappedProfessors);
      }
    } catch (error) {
      console.error("Error fetching professors:", error);
    }
  };

  const runAutomation = async (payload: any) => {
    setIsChecking(true);
    try {
      // 1) optional: check current conflicts before generation
      await apiService.checkConflicts({
        school_year: settings.schoolYear,
        semester: settings.semester,
      });

      // 2) auto-generate (server returns proposed schedules + conflicts[] if any)
      const res = await apiService.autoGenerate({
        ...payload,
        school_year: settings.schoolYear,
        semester: settings.semester,
      });

      if (res.success) {
        // server may persist and/or return the generated schedules
        await fetchSchedules();
        toast({ title: "Automation complete", description: res.message || "Generated schedules successfully." });
        setIsAutoDialogOpen(false);
      } else {
        toast({ title: "Automation failed", description: res.message || "See server logs.", variant: "destructive" });
      }
    } catch (e:any) {
      toast({ title: "Error", description: e?.message || "Automation error.", variant: "destructive" });
    } finally {
      setIsChecking(false);
    }
  };

  const deleteSchedule = async () => {
    if (!scheduleToDelete) return;

    try {
      const response = await apiService.deleteSchedule(
        parseInt(scheduleToDelete)
      );
      if (response.success) {
        setSchedules(
          schedules.filter((s) => s.schedule_id !== scheduleToDelete)
        );
        toast({
          title: "Success",
          description: "Schedule deleted successfully",
        });
      } else {
        toast({
          title: "Error",
          description: "Failed to delete schedule",
          variant: "destructive",
        });
      }
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to delete schedule",
        variant: "destructive",
      });
    } finally {
      setIsDeleteOpen(false);
      setScheduleToDelete(null);
    }
  };

  const clearFilters = () => {
    setFilters({
      search: "",
      professor: "all",
      level: "all",
      strand: "all",
      status: "all",
    });
  };

  // Effects
  useEffect(() => {
    fetchSchedules();
    fetchProfessors();
  }, [settings.schoolYear, settings.semester]);

  // Render schedule card
  const renderScheduleCard = (schedule: Schedule) => (
    <Card
      key={schedule.schedule_id}
      className="hover:shadow-md transition-shadow"
    >
      <CardHeader className="pb-3">
        <div className="flex items-start justify-between">
          <div>
            <CardTitle className="text-lg">{schedule.section_name}</CardTitle>
            <p className="text-sm text-muted-foreground">
              {schedule.level} - {schedule.strand}
            </p>
          </div>
          {getStatusBadge(schedule)}
        </div>
      </CardHeader>

      <CardContent className="space-y-3">
        <div className="flex items-center gap-2">
          <BookOpen className="h-4 w-4 text-muted-foreground" />
          <div>
            <p className="font-medium text-sm">{schedule.subj_code}</p>
            <p className="text-xs text-muted-foreground">
              {schedule.subj_name}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Users className="h-4 w-4 text-muted-foreground" />
          <p className="text-sm">{schedule.professor_name}</p>
        </div>

        <div className="flex items-center gap-2">
          <Clock className="h-4 w-4 text-muted-foreground" />
          <p className="text-sm">
            {formatTime(schedule.start_time)} - {formatTime(schedule.end_time)}
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Calendar className="h-4 w-4 text-muted-foreground" />
          <div className="flex flex-wrap gap-1">
            {schedule.days.map((day) => (
              <Badge key={day} variant="outline" className="text-xs">
                {day.slice(0, 3)}
              </Badge>
            ))}
          </div>
        </div>

        {schedule.room_number && (
          <div className="flex items-center gap-2">
            <MapPin className="h-4 w-4 text-muted-foreground" />
            <p className="text-sm">{schedule.room_number}</p>
          </div>
        )}

        <div className="flex gap-2 pt-2">
          <Button
            size="sm"
            variant="outline"
            onClick={() => {
              setSelectedSchedule(schedule);
              setIsDetailsOpen(true);
            }}
          >
            <Eye className="h-3 w-3 mr-1" />
            View
          </Button>
          <Button
            size="sm"
            variant="destructive"
            onClick={() => {
              setScheduleToDelete(schedule.schedule_id);
              setIsDeleteOpen(true);
            }}
          >
            <Trash2 className="h-3 w-3 mr-1" />
            Delete
          </Button>
        </div>
      </CardContent>
    </Card>
  );

  // Render schedule table
  const renderScheduleTable = () => (
    <div className="rounded-lg border bg-white">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Section</TableHead>
            <TableHead>Subject</TableHead>
            <TableHead>Professor</TableHead>
            <TableHead>Time</TableHead>
            <TableHead>Days</TableHead>
            <TableHead>Room</TableHead>
            <TableHead>Status</TableHead>
            <TableHead>Actions</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {filteredSchedules.map((schedule) => (
            <TableRow key={schedule.schedule_id}>
              <TableCell>
                <div>
                  <p className="font-medium">{schedule.section_name}</p>
                  <p className="text-xs text-muted-foreground">
                    {schedule.level} - {schedule.strand}
                  </p>
                </div>
              </TableCell>
              <TableCell>
                <div>
                  <p className="font-medium">{schedule.subj_code}</p>
                  <p className="text-xs text-muted-foreground">
                    {schedule.subj_name}
                  </p>
                </div>
              </TableCell>
              <TableCell>{schedule.professor_name}</TableCell>
              <TableCell>
                {formatTime(schedule.start_time)} -{" "}
                {formatTime(schedule.end_time)}
              </TableCell>
              <TableCell>
                <div className="flex gap-1">
                  {schedule.days.slice(0, 3).map((day) => (
                    <Badge key={day} variant="outline" className="text-xs">
                      {day.slice(0, 3)}
                    </Badge>
                  ))}
                  {schedule.days.length > 3 && (
                    <Badge variant="outline" className="text-xs">
                      +{schedule.days.length - 3}
                    </Badge>
                  )}
                </div>
              </TableCell>
              <TableCell>{schedule.room_number || "No Room"}</TableCell>
              <TableCell>{getStatusBadge(schedule)}</TableCell>
              <TableCell>
                <div className="flex gap-1">
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => {
                      setSelectedSchedule(schedule);
                      setIsDetailsOpen(true);
                    }}
                  >
                    <Eye className="h-3 w-3" />
                  </Button>
                  <Button
                    size="sm"
                    variant="destructive"
                    onClick={() => {
                      setScheduleToDelete(schedule.schedule_id);
                      setIsDeleteOpen(true);
                    }}
                  >
                    <Trash2 className="h-3 w-3" />
                  </Button>
                </div>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="container mx-auto py-6 px-4 space-y-6">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
          <div>
            <h1 className="text-2xl font-bold">Class Schedules</h1>
            <p className="text-muted-foreground">
              {settings.schoolYear} - {settings.semester}
            </p>
          </div>
          <div className="flex gap-2">
            <Button
              variant="outline"
              onClick={fetchSchedules}
              disabled={loading}
            >
              <RefreshCw
                className={`mr-2 h-4 w-4 ${loading ? "animate-spin" : ""}`}
              />
              Refresh
            </Button>
            <Button
              variant="outline"
              onClick={syncToMobile}
              disabled={isSyncing}
              className="bg-blue-50 border-blue-200 text-blue-700 hover:bg-blue-100"
            >
              <Smartphone
                className={`mr-2 h-4 w-4 ${isSyncing ? "animate-pulse" : ""}`}
              />
              {isSyncing ? "Syncing..." : "Sync to Mobile"}
            </Button>
            <Button onClick={() => navigate("/scheduling/new")}>
              <Plus className="mr-2 h-4 w-4" />
              Add Schedule
            </Button>
            <Button variant="outline" onClick={() => setIsAutoDialogOpen(true)}>
              Auto-Generate
            </Button>
          </div>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">
                    Total Schedules
                  </p>
                  <p className="text-2xl font-bold">{stats.total}</p>
                </div>
                <Calendar className="h-8 w-8 text-blue-500" />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">
                    Today's Classes
                  </p>
                  <p className="text-2xl font-bold">{stats.today}</p>
                </div>
                <Clock className="h-8 w-8 text-green-500" />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-muted-foreground">Conflicts</p>
                  <p className="text-2xl font-bold text-red-600">
                    {stats.conflicts}
                  </p>
                </div>
                <AlertTriangle className="h-8 w-8 text-red-500" />
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Filters */}
        <Card>
          <CardContent className="p-4">
            <div className="flex flex-col md:flex-row gap-4">
              {/* Search */}
              <div className="flex-1">
                <div className="relative">
                  <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                  <Input
                    placeholder="Search schedules..."
                    value={filters.search}
                    onChange={(e) =>
                      setFilters((prev) => ({
                        ...prev,
                        search: e.target.value,
                      }))
                    }
                    className="pl-10"
                  />
                </div>
              </div>

              {/* Quick Filters */}
              <div className="flex gap-2">
                <Select
                  value={filters.professor}
                  onValueChange={(value) =>
                    setFilters((prev) => ({ ...prev, professor: value }))
                  }
                >
                  <SelectTrigger className="w-[140px]">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All Professors</SelectItem>
                    {professors.map((prof) => (
                      <SelectItem key={prof.id} value={prof.name}>
                        {prof.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>

                <Select
                  value={filters.level}
                  onValueChange={(value) =>
                    setFilters((prev) => ({ ...prev, level: value }))
                  }
                >
                  <SelectTrigger className="w-[100px]">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All Levels</SelectItem>
                    <SelectItem value="11">Grade 11</SelectItem>
                    <SelectItem value="12">Grade 12</SelectItem>
                  </SelectContent>
                </Select>

                <Select
                  value={filters.strand}
                  onValueChange={(value) =>
                    setFilters((prev) => ({ ...prev, strand: value }))
                  }
                >
                  <SelectTrigger className="w-[100px]">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All Strands</SelectItem>
                    <SelectItem value="STEM">STEM</SelectItem>
                    <SelectItem value="HUMSS">HUMSS</SelectItem>
                    <SelectItem value="GAS">GAS</SelectItem>
                    <SelectItem value="ABM">ABM</SelectItem>
                  </SelectContent>
                </Select>

                <Select
                  value={filters.status}
                  onValueChange={(value) =>
                    setFilters((prev) => ({ ...prev, status: value }))
                  }
                >
                  <SelectTrigger className="w-[100px]">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All Status</SelectItem>
                    <SelectItem value="good">Good</SelectItem>
                    <SelectItem value="conflict">Conflict</SelectItem>
                  </SelectContent>
                </Select>

                {(filters.search ||
                  filters.professor !== "all" ||
                  filters.level !== "all" ||
                  filters.strand !== "all" ||
                  filters.status !== "all") && (
                  <Button variant="outline" onClick={clearFilters}>
                    <X className="h-4 w-4" />
                  </Button>
                )}
              </div>
            </div>

            {/* View Toggle & Results */}
            <div className="flex items-center justify-between mt-4">
              <p className="text-sm text-muted-foreground">
                Showing {filteredSchedules.length} of {schedules.length}{" "}
                schedules
              </p>

              <div className="flex gap-2">
                <Button
                  size="sm"
                  variant={viewMode === "cards" ? "default" : "outline"}
                  onClick={() => setViewMode("cards")}
                >
                  <Grid3X3 className="h-4 w-4" />
                </Button>
                <Button
                  size="sm"
                  variant={viewMode === "table" ? "default" : "outline"}
                  onClick={() => setViewMode("table")}
                >
                  <List className="h-4 w-4" />
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Content */}
        {loading ? (
          <div className="flex items-center justify-center h-64">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
          </div>
        ) : filteredSchedules.length === 0 ? (
          <Card>
            <CardContent className="p-12 text-center">
              <Calendar className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
              <h3 className="text-lg font-semibold mb-2">No schedules found</h3>
              <p className="text-muted-foreground mb-4">
                {schedules.length === 0
                  ? "Create your first schedule to get started."
                  : "Try adjusting your filters to see more results."}
              </p>
              <Button onClick={() => navigate("/scheduling/new")}>
                <Plus className="mr-2 h-4 w-4" />
                Add Schedule
              </Button>
            </CardContent>
          </Card>
        ) : viewMode === "cards" ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {filteredSchedules.map(renderScheduleCard)}
          </div>
        ) : (
          renderScheduleTable()
        )}

        {/* Schedule Details Dialog */}
        <Dialog open={isDetailsOpen} onOpenChange={setIsDetailsOpen}>
          <DialogContent className="max-w-md">
            <DialogHeader>
              <DialogTitle>Schedule Details</DialogTitle>
            </DialogHeader>

            {selectedSchedule && (
              <div className="space-y-4">
                <div>
                  <h3 className="font-semibold text-lg">
                    {selectedSchedule.section_name}
                  </h3>
                  <p className="text-muted-foreground">
                    {selectedSchedule.level} - {selectedSchedule.strand}
                  </p>
                </div>

                <div className="space-y-3">
                  <div className="flex items-center gap-2">
                    <BookOpen className="h-4 w-4 text-muted-foreground" />
                    <div>
                      <p className="font-medium">
                        {selectedSchedule.subj_code}
                      </p>
                      <p className="text-sm text-muted-foreground">
                        {selectedSchedule.subj_name}
                      </p>
                    </div>
                  </div>

                  <div className="flex items-center gap-2">
                    <Users className="h-4 w-4 text-muted-foreground" />
                    <p>{selectedSchedule.professor_name}</p>
                  </div>

                  <div className="flex items-center gap-2">
                    <Clock className="h-4 w-4 text-muted-foreground" />
                    <p>
                      {formatTime(selectedSchedule.start_time)} -{" "}
                      {formatTime(selectedSchedule.end_time)}
                    </p>
                  </div>

                  <div className="flex items-center gap-2">
                    <Calendar className="h-4 w-4 text-muted-foreground" />
                    <div className="flex gap-1">
                      {selectedSchedule.days.map((day) => (
                        <Badge key={day} variant="outline">
                          {day}
                        </Badge>
                      ))}
                    </div>
                  </div>

                  {selectedSchedule.room_number && (
                    <div className="flex items-center gap-2">
                      <MapPin className="h-4 w-4 text-muted-foreground" />
                      <p>{selectedSchedule.room_number}</p>
                    </div>
                  )}

                  <div className="flex items-center gap-2">
                    <span className="text-sm font-medium">Status:</span>
                    {getStatusBadge(selectedSchedule)}
                  </div>
                </div>
              </div>
            )}

            <DialogFooter>
              <Button variant="outline" onClick={() => setIsDetailsOpen(false)}>
                Close
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        {/* Delete Confirmation */}
        <AlertDialog open={isDeleteOpen} onOpenChange={setIsDeleteOpen}>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Delete Schedule</AlertDialogTitle>
              <AlertDialogDescription>
                Are you sure you want to delete this schedule? This action
                cannot be undone.
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Cancel</AlertDialogCancel>
              <AlertDialogAction
                onClick={deleteSchedule}
                className="bg-red-600 hover:bg-red-700"
              >
                Delete
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>

        <AutoGenerateDialog
          open={isAutoDialogOpen}
          onOpenChange={setIsAutoDialogOpen}
          onRun={runAutomation}
          defaults={{ school_year: settings.schoolYear, semester: settings.semester }}
        />
      </div>
    </div>
  );
};

export default ScheduleManagement;
